### ISSUE TITLE
Investigate generated Kotlin "module" file name

### ISSUE THREAD

**Issue by Zhuinden** [Zhuinden/livedata-validateby-kt#1]
https://blog.jetbrains.com/kotlin/2015/09/kotlin-m13-is-out/

> More than one file was found with OS independent path 'META-INF/build.kotlin_module'.

This is happening and I think it has to be because of the move to JVM-libraries, apparently Kotlin gets confused.

I might need to build a hotfix version for all 6 of the helper libs.

**Comment by KaustubhPatange** [comment]
Do we get this compiler issue when we apply library to one of our module or it is an internal thing?

**Comment by Zhuinden** [comment]
I was getting this:

> more than one file was found with os independent path 'meta-inf/build.kotlin_module'

And I think it might happen when you add 2+ of any of the `validateby-kt`/`combinetuple-kt`/`ziptuple-kt` libraries, I think it has to be some kind of misconfiguration when I made the libraries JVM-only.

I found myself having to add 

```
    packagingOptions {
        exclude 'META-INF/*.kotlin_module'
    }
```

which is most likely not correct nor expected, so if my hunch is correct, I think I'll have to apply a fix based on https://stackoverflow.com/a/56329676/2413303 so that these kotlin_modules stop being called `build` for whatever reason.

So not internal, I just need to get back home to do something about it. Not even sure if just adding some compiler flag will fix it: it's already weird that it adds a silly name instead of like, using the project name by default.

**Comment by Zhuinden** [comment]
Okay so now I checked and it's

>     META-INF\livedata-validateby-kt_release.kotlin_module

So I don't know where the issue is coming from, but not from me?

Anyway, if anyone encounters this, `pickFirst` is probably a better choice than `exclude`.

**Comment by Zhuinden** [comment]
It was actually an issue in the artifacts generated on Jitpack, but this was actually pretty much the only Lib unaffected.

Had to update tuples-kt, *-combineTuple-kt, and *-validateBy-Kt, and *-zipTuple-kt libraries.
